#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/c/Program Files/nodejs:$PATH"

if ! npx prettier --write .; then
  echo "Error: Code formatting failed. Please fix the issues before committing."
  exit 1
fi
if ! npm run build; then
  echo "Error: Code building failed. Please fix the issues before committing."
  exit 1
fi
if ! npm run lint; then
  echo "Error: Linting failed. Please fix the issues before committing."
  exit 1
fi

git pull origin develop
